version: '3.8'

services:
  las-validator:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: las-validator-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      # Optional: Mount uploads directory for persistence
      - ./uploads:/app/uploads
      # Optional: Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - las-network


networks:
  las-network:
    driver: bridge

volumes:
  uploads:
    driver: local
  logs:
    driver: local