version: '3.8'

services:
  las-validator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: las-validator-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      # Mount for development (optional - comment out for production)
      - ./static:/app/static:ro
      - ./templates:/app/templates:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - las-network

networks:
  las-network:
    driver: bridge